// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AddFlairJson { name: string, display_name: string, path: string | null, community_actor_id: string, mod_only: boolean, }