// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DeleteUserFlairJson { user_actor_id: string, community_actor_id: string, instance_domain: string, }