// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FlairDirectory { id: number | null, special: boolean, ref_id: string, pos: number, flair: number, path: string | null, }