// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserFlair { user_actor_id: string, flair_name: string, flair_community_actor_id: string, assigned_on: string, }