// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserFlair { id: number | null, user_actor_id: number, flair_id: number, assigned_on: string, }